wandb_version: 1

entloss_coef:
  value: 0.05
eps_clip:
  value: 0.2
feature_set:
  value: LBs,finished_mark,weighted_priorities,normalized_weights,remaining_weighted_work,machine_contention
hidden_dim:
  value: 128
hidden_dim_actor:
  value: 64
hidden_dim_critic:
  value: 32
k_epochs:
  value: 1
log_every:
  value: 50
lr:
  value: 1.0e-05
max_updates:
  value: 1000
num_envs:
  value: 16
num_layers:
  value: 3
num_mlp_layers_actor:
  value: 2
num_mlp_layers_critic:
  value: 2
num_mlp_layers_feature_extract:
  value: 2
