wandb_version: 1

high:
  value: 99
low:
  value: 1
max_updates:
  value: 100
n_j:
  value: 6
n_m:
  value: 6
np_seed_train:
  value: 200
np_seed_validation:
  value: 200
num_envs:
  value: 4
output_dir:
  value: results/uniform_weights/environment_sweeps/20250326_200448
rewardscale:
  value: 0.07868850563482888
torch_seed:
  value: 600
validate_every:
  value: 20
weight_high:
  value: 1
weight_low:
  value: 1
