wandb_version: 1

entloss_coef:
  value: 0.01
eps_clip:
  value: 0.2
feature_set:
  value: LBs,finished_mark,weighted_priorities
hidden_dim:
  value: 64
hidden_dim_actor:
  value: 32
hidden_dim_critic:
  value: 32
k_epochs:
  value: 1
log_every:
  value: 100
lr:
  value: 1.0e-05
max_updates:
  value: 2000
num_envs:
  value: 16
num_layers:
  value: 3
num_mlp_layers_actor:
  value: 2
num_mlp_layers_critic:
  value: 2
num_mlp_layers_feature_extract:
  value: 2
