wandb_version: 1

feature_set:
  value: LBs,finished_mark,normalized_weights,weighted_priorities
max_updates:
  value: 100
output_dir:
  value: results/uniform_weights/feature_sweeps/20250327_185057
validate_every:
  value: 20
