program: scripts/train.py
method: bayes
metric:
  name: validation_weighted_sum
  goal: minimize
parameters:
  n_j:
    values: [6]
  n_m:
    values: [6]
  low:
    values: [1]
  high:
    values: [99]
  rewardscale:
    distribution: uniform
    min: 0.0
    max: 0.5
  np_seed_train:
    values: [200]
  np_seed_validation:
    values: [200]
  torch_seed:
    values: [600]
  max_updates:
    values: [1000, 5000, 10000]
  num_envs:
    values: [4, 8, 16]