program: scripts/train.py
method: grid
metric:
  name: best_validation_weighted_sum
  goal: minimize
parameters:
  feature_set:
    values: 
      - LBs,finished_mark
      - LBs,finished_mark,normalized_weights
      - LBs,finished_mark,weighted_priorities
      - LBs,finished_mark,normalized_weights,weighted_priorities
      - LBs,finished_mark,normalized_weights,machine_contention
      - LBs,finished_mark,normalized_weights,weighted_priorities,remaining_weighted_work
      - weighted_LBs,finished_mark
      - LBs,finished_mark,weighted_priorities_normalized
      - LBs,finished_mark,weighted_priorities,machine_contention
      - LBs,finished_mark,weighted_priorities,critical_path_contribution
      - LBs,finished_mark,weighted_priorities,time_elapsed
      - LBs,finished_mark,normalized_weights,last_op_weighted
      - weighted_LBs,finished_mark,normalized_weights,weighted_priorities
      - LBs,finished_mark,normalized_weights,weighted_priorities,critical_path_contribution
      - weighted_LBs,finished_mark,remaining_weighted_work,last_op_weighted
      - LBs,finished_mark,normalized_weights,weighted_priorities,time_elapsed,machine_contention
      - LBs,weighted_LBs,finished_mark,weighted_priorities,normalized_weights,remaining_weighted_work, time_elapsed, machine_contention, weighted_priorities_normalized, last_op_weighted, critical_path_contribution