program: scripts/train.py
method: random
metric:
  name: validation_weighted_sum
  goal: minimize
parameters:
  feature_set:
    values: 
      - LBs,finished_mark
      - LBs,finished_mark,normalized_weights
      - LBs,finished_mark,weighted_priorities
      - LBs,finished_mark,normalized_weights,weighted_priorities
      - LBs,finished_mark,normalized_weights,machine_contention
      - LBs,finished_mark,normalized_weights,weighted_priorities,remaining_weighted_work
      - weighted_LBs,finished_mark
      - LBs,finished_mark,weighted_priorities_normalized
      - LBs,finished_mark,weighted_priorities,machine_contention
      - LBs,finished_mark,weighted_priorities,critical_path_contribution
      - LBs,finished_mark,weighted_priorities,time_elapsed