program: scripts/train.py
method: grid
metric:
  name: best_validation_weighted_sum
  goal: minimize
parameters:
  reward_strategy:
    values: [
      "default",
      "wspt_guided",
      "potential_based",
      "critical_path",
      "wspt",
      "weighted_delay",
      "direct_weighted_sum",
      "look_ahead"
    ]