wandb_version: 1

feature_set:
  value: LBs,finished_mark,weighted_priorities,machine_contention
max_updates:
  value: 100
output_dir:
  value: results/uniform_weights/feature_sweeps/20250328_000031
validate_every:
  value: 20
